### ISSUE TITLE
Vertical Metrics revision

### ISSUE THREAD

**Issue by vv-monsalve** [guidoferreyra/Geist#1]
Hi @guidoferreyra,

After pulling the latest files at commit 4a7d292 and giving them an initial revision in preparation for the GF onboarding, the line height looks a bit tight. I recommend revising it.

Even though they meet the minimal requirement of 120%, we strongly recommend setting it to 130% as the safest value. This will allow the font to be updated in the future with added language support, such as Vietnamese. This has already proven to work in some projects. You can find more details about this [here](https://googlefonts.github.io/gf-guide/metrics.html#10-typohheaascender-value-should-leave-open-room-for-stacked-diacritics).

<img width="1519" alt="Screenshot 2024-08-21 at 20 18 28" src="https://github.com/user-attachments/assets/2620b4a1-cdc0-475c-95ed-43f36061221b">

**Comment by guidoferreyra** [comment]
@vv-monsalve can you check it now? I made it 130%

**Comment by vv-monsalve** [comment]
Fonts VM at commit `972ecc2` look good.

**Comment by vv-monsalve** [comment]
Fonts VM at commit `972ecc2` look good.
